### ISSUE TITLE
modus operandi tritanopia and deuteranopia are the same

### ISSUE THREAD

**Issue by zzantares** [anhsirk0/alacritty-themes#1]
I couldn't see any difference when switching between
`modus-operandi-deuteranopia` and `modus-operandi-tritanopia`, they look the
same to me, after diffing the colors, it's eviddent they use the same color palette:

```diff
--- themes/modus-operandi-deuteranopia.yaml     2023-09-04 13:18:50.017296796 -0600
+++ themes/modus-operandi-tritanopia.yaml       2023-09-04 13:18:50.017296796 -0600
@@ -1,4 +1,4 @@
-# Colors Modus-Operandi-Deuteranopia
+# Colors Modus-Operandi-Tritanopia
 colors:
   normal:
     black: '#f2f2f2'
```

So I thought we should remove the `modus-operandi-tritanopia`, however,
there's a difference between vivendi (dark) variants of the modus themes:

```diff
--- themes/modus-vivendi-deuteranopia.yaml      2023-09-04 13:18:50.017296796 -0600
+++ themes/modus-vivendi-tritanopia.yaml        2023-09-04 13:18:50.017296796 -0600
@@ -1,4 +1,4 @@
-# Colors Modus-Vivendi-Deuteranopia
+# Colors Modus-Vivendi-Tritanopia
 colors:
   normal:
     black: '#1e1e1e'
@@ -11,7 +11,7 @@
     white: '#ffffff'
   bright:
     black: '#535353'
-    red: '#ff7f9f'
+    red: '#ff6f9f'
     green: '#00c06f'
     yellow: '#d8af7a'
     blue: '#00bcff'
```

so that now makes me think the `bright.red` somehow needs to be fixed in
`modus-operandi-tritanopia.yaml`, or maybe there's nothing to fix if there's
no red variant to use in the ligth (operandi) variants of the theme?

**Comment by anhsirk0** [comment]
Yeah, they are the same for the most part, and yes `bright.red` is different for only vivendi variants.

I used this script to automatically port themes from  the source themes.
script: https://codeberg.org/anhsirk0/theme-builder
source: https://git.sr.ht/~protesilaos/modus-themes
